### ISSUE TITLE
下载时会报错并卡住

### ISSUE THREAD

**Issue by Godeau233** [acgtools/hanime-hunter#12]
下载一短时间后会报错：
context deadline exceeded (Client.Timeout or context cancellation while reading body)

**Comment by dreamjz** [comment]
啊，我忘了写中文的 issue 模板了，刚加上了
麻烦你，使用 BUG Report 模板：
```
issues -> new issue -> 选择 BUG Report 模板 -> 填写相关信息
```

这样我就可以根据你给的信息直接开始 找原因，不用再额外的询问更多信息了
并且节省双方的时间，提高效率

顺便一提，#11 这个 issue 里面你有提到影视库，我挺感兴趣的，可以告知你用的什么软件么，我可能想做一个里番专用的 影视库之类的软件，然和下载功能结合起来。

**Comment by Godeau233** [comment]
我有一个nas，使用emby影音管理服务器可以利用本地保存的影视文件以及其对应的nfo文件构建影视墙，NFO文件是用来描述多媒体文件（如视频、音乐或游戏）的一个标准的XML文件，它可以包含多种数据，如影片的标题、导演、演员名单、简介、评分、海报链接、屏幕截图等。
![QQ截图20231223230027](https://github.com/acgtools/hanime-hunter/assets/114890890/0ba80394-f681-4619-aae4-465eef2e66cc)
![QQ截图20231223230039](https://github.com/acgtools/hanime-hunter/assets/114890890/a49e0014-8c35-4fd2-a783-73375f9cfb29)
类似上面这种
以下是一个典型的NFO文件的内容示例，该文件描述一个电影：
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<movie>
  <title>The Shawshank Redemption</title>
  <originaltitle>The Shawshank Redemption</originaltitle>
  <sorttitle>Shawshank Redemption, The</sorttitle>
  <set></set>
  <rating>9.3</rating>
  <year>1994</year>
  <top250>#1</top250>
  <votes>2,194,984</votes>
  <outline>Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.</outline>
  <plot>Andy Dufresne is sent to Shawshank Prison for the murder of his wife and her lover. Over the next two decades, he finds a way to live out life with relative ease as he serves the toughest sentence possible in the best way he can.</plot>
  <tagline>Fear can hold you prisoner. Hope can set you free.</tagline>
  <runtime>142</runtime>
  <thumb aspect="poster">http://image.tmdb.org/t/p/original/9O7gLzmreU0nGkIB6K3BsJbzvNv.jpg</thumb>
  <thumb aspect="banner">http://image.tmdb.org/t/p/original/xBKGJQsAIeweesB79KC89FpBrVr.jpg</thumb>
  <fanart>
    <thumb>http://image.tmdb.org/t/p/original/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg</thumb>
  </fanart>
  <mpaa>R</mpaa>
  <country>USA</country>
  <genre>Drama</genre>
  <director>Frank Darabont</director>
  <actor>
    <name>Tim Robbins</name>
    <role>Andy Dufresne</role>
    <thumb>http://image.tmdb.org/t/p/original/hsCu1JUzQQ4pl7uFxAVFLOs9yHh.jpg</thumb>
  </actor>
  <actor>
    <name>Morgan Freeman</name>
    <role>Ellis Boyd 'Red' Redding</role>
    <thumb>http://image.tmdb.org/t/p/original/71czt0XAyBb6WqK8JZAl0zUHS8t.jpg</thumb>
  </actor>
  
  <studio>Columbia Pictures</studio>
  <trailer>https://www.youtube.com/watch?v=NmzuHjWmXOc</trailer>
</movie>
`

**Comment by Godeau233** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<movie>
  <title>The Shawshank Redemption</title>
  <originaltitle>The Shawshank Redemption</originaltitle>
  <sorttitle>Shawshank Redemption, The</sorttitle>
  <set></set>
  <rating>9.3</rating>
  <year>1994</year>
  <top250>#1</top250>
  <votes>2,194,984</votes>
  <outline>Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.</outline>
  <plot>Andy Dufresne is sent to Shawshank Prison for the murder of his wife and her lover. Over the next two decades, he finds a way to live out life with relative ease as he serves the toughest sentence possible in the best way he can.</plot>
  <tagline>Fear can hold you prisoner. Hope can set you free.</tagline>
  <runtime>142</runtime>
  <thumb aspect="poster">http://image.tmdb.org/t/p/original/9O7gLzmreU0nGkIB6K3BsJbzvNv.jpg</thumb>
  <thumb aspect="banner">http://image.tmdb.org/t/p/original/xBKGJQsAIeweesB79KC89FpBrVr.jpg</thumb>
  <fanart>
    <thumb>http://image.tmdb.org/t/p/original/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg</thumb>
  </fanart>
  <mpaa>R</mpaa>
  <country>USA</country>
  <genre>Drama</genre>
  <director>Frank Darabont</director>
  <actor>
    <name>Tim Robbins</name>
    <role>Andy Dufresne</role>
    <thumb>http://image.tmdb.org/t/p/original/hsCu1JUzQQ4pl7uFxAVFLOs9yHh.jpg</thumb>
  </actor>
  <actor>
    <name>Morgan Freeman</name>
    <role>Ellis Boyd 'Red' Redding</role>
    <thumb>http://image.tmdb.org/t/p/original/71czt0XAyBb6WqK8JZAl0zUHS8t.jpg</thumb>
  </actor>
  
  <studio>Columbia Pictures</studio>
  <trailer>https://www.youtube.com/watch?v=NmzuHjWmXOc</trailer>
</movie>

**Comment by Godeau233** [comment]
如果在pc端构建影视库/影视墙的话可以用kodi

**Comment by dreamjz** [comment]
谢谢，学到新东西了👍  看了下 kodi，感觉 功能太强了 😊

**Comment by dreamjz** [comment]
我计划下个版本添加 NFO 生成功能，所以 Reopen this issue ^_^

**Comment by dreamjz** [comment]
抱歉, 应开重开的是 #11, 尴尬
