### ISSUE TITLE
[BUG] The last file sometimes ends with `octet-stream` not `mp4` during series batch downloading

### ISSUE THREAD

**Issue by Kirrito-k423** [acgtools/hanime-hunter#26]
### 描述出现的问题

如图，系列下载时。假如最新的文件是最近发布，**有时**该文件会以`octet-stream`结尾

### 截图 (可选)
![image](https://github.com/acgtools/hanime-hunter/assets/44373239/661a3d17-603a-4545-8cdd-974369fdbb2c)

### 运行环境
如上图

**Comment by Kirrito-k423** [comment]
好像这个问题，我现在没遇到了。一开始遇到蛮多

**Comment by Kirrito-k423** [comment]
还是会出现，触发情况不是很清楚。有是有有时没有。我出现这种情况的链接 [https://hanime1.me/watch?v=6826](hanime)

**Comment by dreamjz** [comment]
Thank you for your report.

网站有的文件 `Content-Type` 给的 `application/octet-stream`，有的是 `video/mp4` , 实际上二进制内容没问题，我改下文件扩展为 mp4 就行。
