### ISSUE TITLE
[BUG] 下载后缀名为octet-stream

### ISSUE THREAD

**Issue by blindlight86** [acgtools/hanime-hunter#31]
### 描述出现的问题

下载后缀名为octet-stream

hanime1提供了错误的的Content-Type，如：https://hanime1.me/watch?v=85831
```Content-Type: application/octet-stream```

看代码中直接使用了网站提供的Content-Type

https://github.com/acgtools/hanime-hunter/blob/a855c1443af69279332d6449996840304553c7c9/internal/resolvers/hanime1me/hanime1me.go#L255

**Comment by dreamjz** [comment]
Thank you for your report.

I'll fix it in next version.
