### ISSUE TITLE
文件保存位置需要优化

### ISSUE THREAD

**Issue by yundabei** [acgtools/hanime-hunter#9]
需求: 1. 加入一个默认的保存目录,比如~/hani_downloads/
2. 加入可以下载完成后执行命令的配置

我是在服务器上使用这个项目的,我不想在根目录直接使用命令并下载,因为这样的话会直接在根目录创建文件夹,每次使用时都需要先切到 ~/downloads/ 文件夹,下载后使用rclone命令进行上传该文件夹下的所有内容.所以可不可以加入一个固定的输出路径,或者有 config 之类的文件可以自行配置.
如果可以加入下载完成后执行命令这个功能就可以在下载完成后自动执行 rclone 的上传命令.我现在是使用crontab命令每天00:00执行rclone的上传命令

命令如下 : 0 0 * * * /usr/bin/rclone move ~/本地地址/ yundabei:/远程文件夹名称 --delete-empty-src-dirs

**Comment by dreamjz** [comment]
Thank you for your issue.

> 1. 加入一个默认的保存目录,比如~/hani_downloads/

You can use `-o`/`--output-dir` flag to specify the output directory, Here is the description in [README](https://github.com/acgtools/hanime-hunter?tab=readme-ov-file#specify-the-output-directory)

```sh
# The video will be saved in ~/hani-dl/anime_foo/anime_foo_02.mp4
$ hani dl -o ~/hani-dl xxx/anime_foo_02
```

> 2. 加入可以下载完成后执行命令的配置

I don't want to add this feature, becasuse:
1. The behavior of user-customized commands is unpredictable, making it difficult to handle the errors.
2. Executing user-customized cmd will increase the complexity of this tool, making the code difficult to maintain.
3. Executing user-customized cmd is not in the scope of this tool.

For alterlative, I think you can write the shell script like this:
```sh
#!/usr/bin/env sh
echo Start hani

hani dl -o ~/hani_downloads/ xxx

echo Start copying files

/usr/bin/rclone move ~/本地地址/ yundabei:/远程文件夹名称 --delete-empty-src-dirs

echo Done
```

> 1. 加入一个默认的保存目录,比如~/hani_downloads/

你可以用 `-o`/`--output-dir` 来指定输出路径, 这是在文档中的介绍 [README](https://github.com/acgtools/hanime-hunter?tab=readme-ov-file#specify-the-output-directory)

```sh
# 视频文件将保存在 ~/hani-dl/anime_foo/anime_foo_02.mp4
$ hani dl -o ~/hani-dl xxx/anime_foo_02
```

> 2. 加入可以下载完成后执行命令的配置

我不想要添加这个功能，因为:
1. 用户自定义的 command 的行为不可预测，很难去处理出现的错误
2. 用户自定义的 command 会让程序的复杂度增加, 让代码变得难以维护.
3. 执行用户自定义的 command 不在这个程序的功能范围之内.

作为替代, 我觉得你可以写一个这样的 shell 脚本:
```sh
#!/usr/bin/env sh
echo Start hani

hani dl -o ~/hani_downloads/ xxx

echo Start copying files

/usr/bin/rclone move ~/本地地址/ yundabei:/远程文件夹名称 --delete-empty-src-dirs

echo Done
```

**Comment by yundabei** [comment]
非常感谢回复和解答
